# shibcert.yml: shibcert application user-specific configuration

flag:
  use_pin_generate: false  # PINをローカルで生成して申請するフラグ(生成:true)
  use_upki_pass: true      # UPKI-PASS設定を表示するフラグ(非表示:false)
  use_vlan: false          # VLAN設定を表示するフラグ(非表示:false/use_upki_passがfalseの時のみ利用可能)
#  admin_page_num: 20        # 管理者ページのページングサイズ(推奨:20)
  admin_page_num: 2        # 管理者ページのページングサイズ(試験用:2)

label:
  ja:
    site_title: "学認連携: クライアント証明書発行申請システム"
    purpose:
      # 4: Personal Certification SHA1, 5: Client Certification SHA2
      # 6: S/MIME Certificatino SHA1, 7: S/MIME Certification SHA2
      5: "認証用 クライアント証明書"  
      7: "メール暗号化/署名用 S/MIME証明書"
      55: "UPKI-PASS一括用 UPKI-PASS証明書 [UPKI-PASS管理者用]"  
    intro_text: "クライアント証明書とは、PC・タブレット・スマートフォンなどのコンピュータにインストールして電子的な本人確認ができるようにするデジタル証明書です。"
  en:
    site_title: "GakuNin: Client Certificate Enrollment System"  
    purpose:
      # 4: Personal Certificate SHA1, 5: Client Certification SHA2 
      # 6: S/MIME Certificate SHA1, 7: S/MIME Certification SHA2
      5: "Client Certificate for Auth"  
      7: "S/MIME Certificate for Mail"
      55: "Bulk Client Certificate for UPKI-PASS"  
    intro_text: "\"Client Certificate\" is a digital certificate for personal identification which can be installed on computers like PCs/tablets/smartphones."

production:

  certificate_file: "config/certificates/client.cer"
  certificate_key_file:  "config/certificates/client.key"

  cert_download_type: '1'
  admin_name: 'g-cert-dev.gakunin.nii.ac.jp'
  admin_ou: 'UPKI Client Cert Enrollment System Develop'
  admin_mail: 'gcertsys@langedge.jp'
  admin_pass_mail: 'contact@langedge.jp'
  user_ou: 'UPKI Client Cert Enrollment System Develop'

  base_dn_dev: ''
  base_dn_auth: OU=UPKI Client Cert Enrollment System Develop,O=National Institute of Informatics,L=Tokyo,C=JP
  base_dn_smime: OU=UPKI Client Cert Enrollment System Develop,O=National Institute of Informatics,L=Tokyo,C=JP

  # メール連携設定
  mail_basic_name: 'gcertsys'
  mail_basic_pswd: ''

  # UPKI-PASS連携設定
  upki_pass_key1: ''
  upki_pass_key2: ''
  upki_pass_url: 'https://g-cert-dev.gakunin.nii.ac.jp/upki-pass'

  # 管理者設定
  admin_uid1: ''                   # 管理者(1人目)のUid指定(Uidはeppnが使われる)
  admin_uid2: ''                   # 管理者(2人目)のUid指定(Uidはeppnが使われる)
  admin_basic_name: 'gcadmin'
  admin_basic_pswd: ''

development:

  certificate_file: "config/certificates/client.cer"
  certificate_key_file:  "config/certificates/client.key"

  cert_download_type: '1'
  admin_name: 'g-cert-dev.gakunin.nii.ac.jp'
  admin_ou: 'UPKI Client Cert Enrollment System Develop'
  admin_mail: 'gcertsys@langedge.jp'
  admin_pass_mail: 'contact@langedge.jp'
  user_ou: 'UPKI Client Cert Enrollment System Develop'

  base_dn_dev: OU=dev08
  base_dn_auth: OU=UPKI Client Cert Enrollment System Develop,O=National Institute of Informatics,L=Tokyo,C=JP
  base_dn_smime: OU=UPKI Client Cert Enrollment System Develop,O=National Institute of Informatics,L=Tokyo,C=JP

  # メール連携設定
  mail_basic_name: 'gcertsys'
  mail_basic_pswd: ''

  # UPKI-PASS連携設定
  upki_pass_key1: ''
  upki_pass_key2: ''
  upki_pass_url: 'https://g-cert-dev.gakunin.nii.ac.jp/upki-pass'

  # 管理者設定
  admin_uid1: ''            # 管理者(1人目)のUid指定(Uidはeppnが使われる)
  admin_uid2: ''            # 管理者(2人目)のUid指定(Uidはeppnが使われる)
  admin_basic_name: 'gcadmin'
  admin_basic_pswd: ''

test:

  certificate_file: "config/certificates/client.cer"
  certificate_key_file:  "config/certificates/client.key"

  cert_download_type: '1'
  admin_name: 'g-cert-dev.gakunin.nii.ac.jp'
  admin_ou: 'UPKI Client Cert Enrollment System Develop'
  admin_mail: 'gcertsys@langedge.jp'
  admin_pass_mail: 'contact@langedge.jp'
  user_ou: 'UPKI Client Cert Enrollment System Develop'

  base_dn_dev: 'OU=test00'
  base_dn_auth: OU=UPKI Client Cert Enrollment System Develop,O=National Institute of Informatics,L=Tokyo,C=JP
  base_dn_smime: OU=UPKI Client Cert Enrollment System Develop,O=National Institute of Informatics,L=Tokyo,C=JP

  # メール連携設定
  mail_basic_name: 'gcertsys'
  mail_basic_pswd: ''

  # UPKI-PASS連携設定
  upki_pass_key1: ''
  upki_pass_key2: ''
  upki_pass_url: 'https://g-cert-dev.gakunin.nii.ac.jp/upki-pass'

  # 管理者設定
  admin_uid1: ''           # 管理者(1人目)のUid指定(Uidはeppnが使われる)
  admin_uid2: ''           # 管理者(2人目)のUid指定(Uidはeppnが使われる)
  admin_basic_name: 'gcadmin'
  admin_basic_pswd: ''

