# shibcert.yml: shibcert application user-specific configuration

maintenance_mode: false
#maintenance_mode: true
flag:
  use_pin_generate: false  # PINをローカルで生成して申請するフラグ(生成:true)
  use_upki_pass: false      # UPKI-PASS設定を表示するフラグ(非表示:false)
  use_vlan: true          # VLAN設定を表示するフラグ(非表示:false/use_upki_passがfalseの時のみ利用可能)
  admin_page_num: 20        # 管理者ページのページングサイズ(推奨:20)
#  admin_page_num: 2        # 管理者ページのページングサイズ(試験用:2)

production:
  certificate_file: "config/certificates/client.cer"
  certificate_key_file:  "config/certificates/client.key"

  cert_download_type: '1'
  admin_name: 'shibcert.iimc.kyoto-u.ac.jp'
  admin_ou: 'Institute for Information Management and Communication'
  admin_mail: 'shibcert-sys@iimc.kyoto-u.ac.jp'
  admin_pass_mail: 'shibcert-sys@iimc.kyoto-u.ac.jp'
  user_ou: 'Institute for Information Management and Communication'

  base_dn_dev: ''
  base_dn_auth: O=Kyoto University,L=Kyoto,ST=Kyoto,C=JP
  base_dn_smime: O=Kyoto University,L=Kyoto,ST=Kyoto,C=JP

  # メール連携設定
#  mail_basic_name: '*'  # -> MAIL_BASIC_AUTH_ID
#  mail_basic_pswd: '*'  # -> MAIL_BASIC_AUTH_PW

  # UPKI-PASS連携設定
  upki_pass_key1: ''
  upki_pass_key2: ''
  upki_pass_url: 'https://g-cert-dev.gakunin.nii.ac.jp/upki-pass'

  # 管理者設定
  admin_uids: []
#  admin_basic_name: '*' # -> ADMIN_BASIC_AUTH_ID
#  admin_basic_pswd: '*' # -> ADMIN_BASIC_AUTH_PW

development:

  certificate_file: "config/certificates/client.cer"
  certificate_key_file:  "config/certificates/client.key"

  cert_download_type: '1'
  admin_name: 'shibcert.iimc.kyoto-u.ac.jp'
  admin_ou: 'Institute for Information Management and Communication'
  admin_mail: 'shibcert-sys@iimc.kyoto-u.ac.jp'
  admin_pass_mail: 'shibcert-sys@iimc.kyoto-u.ac.jp'
  user_ou: 'Institute for Information Management and Communication'

  base_dn_dev: dev
  base_dn_auth: O=Kyoto University,L=Kyoto,ST=Kyoto,C=JP
  base_dn_smime: O=Kyoto University,L=Kyoto,ST=Kyoto,C=JP


  # メール連携設定
#  mail_basic_name: '*'  # -> MAIL_BASIC_AUTH_ID
#  mail_basic_pswd: '*'  # -> MAIL_BASIC_AUTH_PW

  # UPKI-PASS連携設定
  upki_pass_key1: ''
  upki_pass_key2: ''
  upki_pass_url: 'https://g-cert-dev.gakunin.nii.ac.jp/upki-pass'

  # 管理者設定
  admin_uids: ['']
#  admin_basic_name: '*' # -> ADMIN_BASIC_AUTH_ID
#  admin_basic_pswd: '*' # -> ADMIN_BASIC_AUTH_PW

test:

  certificate_file: "config/certificates/client.cer"
  certificate_key_file:  "config/certificates/client.key"

  cert_download_type: '1'
  admin_name: 'shibcert.iimc.kyoto-u.ac.jp'
  admin_ou: 'Institute for Information Management and Communication'
  admin_mail: 'shibcert-sys@iimc.kyoto-u.ac.jp'
  admin_pass_mail: 'shibcert-sys@iimc.kyoto-u.ac.jp'
  user_ou: 'Institute for Information Management and Communication'

  base_dn_dev: test
  base_dn_auth: O=Kyoto University,L=Kyoto,ST=Kyoto,C=JP
  base_dn_smime: O=Kyoto University,L=Kyoto,ST=Kyoto,C=JP

  # メール連携設定
#  mail_basic_name: '*'  # -> MAIL_BASIC_AUTH_ID
#  mail_basic_pswd: '*'  # -> MAIL_BASIC_AUTH_PW

  # UPKI-PASS連携設定
  upki_pass_key1: ''
  upki_pass_key2: ''
  upki_pass_url: 'https://g-cert-dev.gakunin.nii.ac.jp/upki-pass'

  # 管理者設定
#  admin_uids: []
#  admin_basic_name: '*' # -> ADMIN_BASIC_AUTH_ID
#  admin_basic_pswd: '*' # -> ADMIN_BASIC_AUTH_PW
